### ISSUE TITLE
File extension API returns extension with period

### ISSUE THREAD

**Issue by sberrevoets** [dduan/Pathos#112]
Not sure if there's some standard around this that I'm missing, but I would expect `fileExtension(ofPath: "myFile.swift")` to return `swift` and not `.swift`. To me, the period is the separator between file name and extension and not part of the extension itself.

**Comment by dduan** [comment]
The behavior is modeled after Python
<img width="691" alt="Screen Shot 2019-06-18 at 11 07 35 PM" src="https://user-images.githubusercontent.com/75067/59740757-e37f7a00-921d-11e9-93ec-d006d1438692.png">
